name: ma_raza_khan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.0
  flutter:
    sdk: flutter
  intro_views_flutter: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  extended_image: ^8.2.1
  carousel_slider_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/jamia1_1.jpeg
    - assets/images/jamia2.jpeg
    - assets/images/jamia1.png
    - assets/images/splash.jpeg
    - assets/images/logo.png

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"